version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
      - wget -q https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip && mv terraform /usr/local/bin/
      - wget -q -O /usr/local/bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64
      - chmod +x /usr/local/bin/terragrunt
      - terraform -v
      - terragrunt -v
  pre_build:
    commands:
      # CodeBuild environment variables
      #   BRANCH_NAME -- GitHub branch that triggered the CodeBuild project
      - |
        if [[ -z "${BRANCH_NAME}" ]]; then
          # extract branch from github webhook
          BRANCH_NAME=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d'/' -f 3)
        fi
      - "echo Triggered Branch: $BRANCH_NAME"
      - TARGET_DIRS=($TARGET_DIRS)
      - IFS=" && " read -a COMMANDS <<< $COMMANDS
      - "echo Target Directories: ${TARGET_DIRS[@]}"
      - "echo Commands: ${COMMANDS[@]}"
  build:
    commands:
      - |
        for dir in "${TARGET_DIRS[@]}"; do
          cd $dir
          for command in "${COMMANDS[@]}"; do
            echo ""
            echo "*************** Executing Command: ${command} ******************"
            echo "******* At directory: ${dir} ********"
            echo "*************************************************"
            $command || exit 1
          done
          cd - > /dev/null 
        done